// ============================================================
// DATA LAYER — All product/category data for Flipkart Clone
// ============================================================

const CATEGORIES = [
  { id: "electronics", name: "Electronics",   icon: "📱", color: "#2874f0" },
  { id: "fashion",     name: "Fashion",        icon: "👗", color: "#fb641b" },
  { id: "home",        name: "Home & Kitchen", icon: "🏠", color: "#388e3c" },
  { id: "books",       name: "Books",          icon: "📚", color: "#7b1fa2" },
  { id: "sports",      name: "Sports",         icon: "⚽", color: "#e53935" },
  { id: "beauty",      name: "Beauty",         icon: "💄", color: "#e91e63" },
  { id: "toys",        name: "Toys",           icon: "🧸", color: "#f57c00" },
  { id: "grocery",     name: "Grocery",        icon: "🛒", color: "#00897b" },
];

// Reliable image CDN — picsum.photos always works offline-friendly via seed
function img(seed, w, h) {
  return `https://picsum.photos/seed/${seed}/${w || 400}/${h || 400}`;
}

const PRODUCTS = [
  // ── Electronics ──────────────────────────────────────────
  {
    id: 1, category: "electronics",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung", price: 124999, originalPrice: 149999, rating: 4.5, reviews: 12847,
    badge: "SuperStar",
    images: [img("galaxy-s24",400), img("samsung2",400), img("samsung3",400)],
    description: "The Samsung Galaxy S24 Ultra features a 200MP camera, 5000mAh battery, and titanium frame. Experience AI-powered photography and the built-in S-Pen.",
    specs: { Display: '6.8" QHD+ Dynamic AMOLED 2X, 120Hz', Processor: "Snapdragon 8 Gen 3", RAM: "12GB", Storage: "256GB", Camera: "200MP + 12MP + 10MP + 50MP", Battery: "5000mAh", OS: "Android 14 (One UI 6.1)" },
    highlights: ["200MP Camera with AI", "Built-in S Pen", "Titanium Frame", "7 years of OS updates"],
    inStock: true,
  },
  {
    id: 2, category: "electronics",
    name: "Apple iPhone 15 Pro",
    brand: "Apple", price: 134900, originalPrice: 159900, rating: 4.6, reviews: 9834,
    badge: "Bestseller",
    images: [img("iphone15",400), img("apple2",400), img("apple3",400)],
    description: "iPhone 15 Pro with A17 Pro chip, titanium design, and pro camera system. Capture stunning photos and videos with the most advanced iPhone ever.",
    specs: { Display: '6.1" Super Retina XDR OLED, ProMotion 120Hz', Processor: "A17 Pro chip", RAM: "8GB", Storage: "128GB", Camera: "48MP Main + 12MP Ultra Wide + 12MP Telephoto", Battery: "3274mAh", OS: "iOS 17" },
    highlights: ["A17 Pro chip", "Titanium design", "USB 3 speed", "Action button"],
    inStock: true,
  },
  {
    id: 3, category: "electronics",
    name: "OnePlus 12 5G",
    brand: "OnePlus", price: 64999, originalPrice: 74999, rating: 4.4, reviews: 6721,
    badge: "Hot Deal",
    images: [img("oneplus12",400), img("oneplus2",400)],
    description: "OnePlus 12 with Snapdragon 8 Gen 3, 100W SUPERVOOC charging, and Hasselblad camera tuning.",
    specs: { Display: '6.82" LTPO AMOLED, 120Hz', Processor: "Snapdragon 8 Gen 3", RAM: "12GB", Storage: "256GB", Camera: "50MP + 48MP + 64MP", Battery: "5400mAh", OS: "OxygenOS 14" },
    highlights: ["100W SUPERVOOC", "50W wireless charge", "Hasselblad Camera", "Alert Slider"],
    inStock: true,
  },
  {
    id: 4, category: "electronics",
    name: "Sony WH-1000XM5 Headphones",
    brand: "Sony", price: 24990, originalPrice: 34990, rating: 4.7, reviews: 8923,
    badge: "Top Rated",
    images: [img("headphones-sony",400), img("sony2",400)],
    description: "Industry-leading noise cancellation with the WH-1000XM5. 30 hours battery life and crystal clear calls.",
    specs: { Type: "Over-ear wireless", "Noise Cancellation": "Yes, Industry Leading", Battery: "30 hours", Connectivity: "Bluetooth 5.2", Weight: "250g", Mic: "8 microphones" },
    highlights: ["30hr battery life", "Best-in-class ANC", "Multipoint connection", "Speak-to-chat"],
    inStock: true,
  },
  {
    id: 5, category: "electronics",
    name: 'LG 55" 4K OLED TV',
    brand: "LG", price: 89990, originalPrice: 129990, rating: 4.5, reviews: 3412,
    badge: "30% Off",
    images: [img("lg-tv",400), img("tv2",400)],
    description: "LG OLED TV with α9 Gen6 AI Processor 4K, perfect black, and Dolby Vision/Atmos support.",
    specs: { Size: "55 inches", Resolution: "4K Ultra HD (3840x2160)", "Panel Type": "OLED", HDR: "Dolby Vision, HDR10, HLG", "Refresh Rate": "120Hz", "Smart TV": "webOS 23", Ports: "4x HDMI 2.1, 3x USB" },
    highlights: ["Perfect Black OLED", "120Hz for gaming", "Dolby Vision IQ", "AI 4K Upscaling"],
    inStock: true,
  },
  {
    id: 6, category: "electronics",
    name: "Apple MacBook Air M3",
    brand: "Apple", price: 114900, originalPrice: 134900, rating: 4.8, reviews: 5612,
    badge: "New Launch",
    images: [img("macbook-m3",400), img("laptop2",400)],
    description: "MacBook Air with M3 chip. Up to 18 hours of battery life, 15.3-inch Liquid Retina display.",
    specs: { Display: '15.3" Liquid Retina 2880x1864', Processor: "Apple M3 chip", RAM: "8GB Unified Memory", Storage: "256GB SSD", Battery: "Up to 18 hours", OS: "macOS Sonoma" },
    highlights: ["M3 chip performance", "18hr battery", "Fanless design", "MagSafe charging"],
    inStock: true,
  },
  {
    id: 21, category: "electronics",
    name: "boAt Rockerz 550 Bluetooth Headphones",
    brand: "boAt", price: 1499, originalPrice: 3990, rating: 4.2, reviews: 45231,
    badge: "62% Off",
    images: [img("boat-headphone",400), img("boat2",400)],
    description: "boAt Rockerz 550 with 20 hours of playback, 40mm dynamic drivers and foldable design.",
    specs: { Type: "Over-ear wireless", Battery: "20 hours", Drivers: "40mm dynamic", Connectivity: "Bluetooth 5.0", Weight: "220g" },
    highlights: ["20hr playback", "40mm drivers", "Foldable design", "Built-in mic"],
    inStock: true,
  },
  {
    id: 22, category: "electronics",
    name: "Realme Narzo 60 5G",
    brand: "Realme", price: 17999, originalPrice: 22999, rating: 4.1, reviews: 8234,
    badge: "5G Ready",
    images: [img("realme60",400), img("realme2",400)],
    description: "Realme Narzo 60 5G with Dimensity 6100+ processor, 64MP camera, and 5000mAh battery.",
    specs: { Display: '6.43" AMOLED 90Hz', Processor: "Dimensity 6100+", RAM: "8GB", Storage: "128GB", Camera: "64MP + 2MP", Battery: "5000mAh", OS: "Realme UI 4.0" },
    highlights: ["5G enabled", "64MP camera", "5000mAh battery", "90Hz AMOLED"],
    inStock: true,
  },
  {
    id: 23, category: "electronics",
    name: "Canon EOS 1500D DSLR Camera",
    brand: "Canon", price: 34990, originalPrice: 44990, rating: 4.5, reviews: 6712,
    badge: "Photographer's Pick",
    images: [img("canon-dslr",400), img("camera2",400)],
    description: "Canon EOS 1500D with 24.1 MP CMOS sensor, built-in Wi-Fi and NFC, DIGIC 4+ image processor.",
    specs: { Sensor: "24.1 MP APS-C CMOS", Processor: "DIGIC 4+", ISO: "100-6400", Video: "Full HD 1080p", Battery: "LP-E10 (500 shots)" },
    highlights: ["24.1 MP sensor", "Wi-Fi + NFC", "Full HD video", "Great for beginners"],
    inStock: true,
  },

  // ── Fashion ──────────────────────────────────────────────
  {
    id: 7, category: "fashion",
    name: "Nike Air Max 270",
    brand: "Nike", price: 12995, originalPrice: 15995, rating: 4.3, reviews: 4521,
    badge: "Trending",
    images: [img("nike-airmax",400), img("nike2",400)],
    description: "Nike Air Max 270 with the largest Max Air unit ever in a lifestyle shoe. All-day comfort.",
    specs: { Type: "Lifestyle Sneaker", Material: "Mesh upper, Foam midsole", Sole: "Rubber outsole", Sizes: "UK 6-12", Colors: "Black, White, Red" },
    highlights: ["Air Max 270 cushioning", "Engineered mesh", "Pull tab at heel", "Foam midsole"],
    inStock: true,
  },
  {
    id: 8, category: "fashion",
    name: "Levi's 501 Original Jeans",
    brand: "Levi's", price: 3299, originalPrice: 4999, rating: 4.2, reviews: 7832,
    badge: "Classic",
    images: [img("levis-jeans",400), img("jeans2",400)],
    description: "The original blue jean since 1873. Straight fit, iconic 5-pocket design.",
    specs: { Fit: "Straight", Material: "100% Cotton Denim", Waist: "28-40", Length: "30-34", Wash: "Medium Stonewash" },
    highlights: ["Original 501 cut", "100% cotton", "Button fly", "Shrink-to-fit option"],
    inStock: true,
  },
  {
    id: 9, category: "fashion",
    name: "Fossil Gen 6 Smartwatch",
    brand: "Fossil", price: 22995, originalPrice: 29995, rating: 4.1, reviews: 2341,
    badge: "Smart Pick",
    images: [img("fossil-watch",400), img("watch2",400)],
    description: "Fossil Gen 6 with Snapdragon 4100+ platform, SpO2 sensor, and Wear OS by Google.",
    specs: { Display: '1.28" AMOLED 416x416', OS: "Wear OS by Google", Sensors: "Heart Rate, SpO2, Accelerometer", Battery: "Up to 24 hours", Water: "3 ATM Water Resistant" },
    highlights: ["SpO2 sensor", "24hr battery", "Google Pay", "GPS enabled"],
    inStock: true,
  },
  {
    id: 24, category: "fashion",
    name: "Peter England Men's Formal Shirt",
    brand: "Peter England", price: 799, originalPrice: 1699, rating: 4.3, reviews: 18932,
    badge: "53% Off",
    images: [img("formal-shirt",400), img("shirt2",400)],
    description: "Peter England slim fit formal shirt in premium cotton fabric. Perfect for office and formal occasions.",
    specs: { Fit: "Slim Fit", Material: "100% Cotton", Sizes: "38-46", Pattern: "Solid", Occasion: "Formal" },
    highlights: ["Premium cotton", "Slim fit", "Easy iron", "Machine washable"],
    inStock: true,
  },
  {
    id: 25, category: "fashion",
    name: "Adidas Ultraboost 22 Running Shoes",
    brand: "Adidas", price: 10999, originalPrice: 17999, rating: 4.4, reviews: 3219,
    badge: "Runner's Choice",
    images: [img("adidas-ultraboost",400), img("adidas2",400)],
    description: "Adidas Ultraboost 22 with BOOST midsole, Primeknit+ upper and Continental rubber outsole.",
    specs: { Type: "Running Shoes", Midsole: "BOOST", Upper: "Primeknit+", Sole: "Continental Rubber", Sizes: "UK 6-12" },
    highlights: ["BOOST cushioning", "Primeknit upper", "Responsive feel", "Continental grip"],
    inStock: true,
  },

  // ── Home & Kitchen ────────────────────────────────────────
  {
    id: 10, category: "home",
    name: "Instant Pot Duo 7-in-1",
    brand: "Instant Pot", price: 7999, originalPrice: 12999, rating: 4.6, reviews: 11234,
    badge: "Kitchen Essential",
    images: [img("instant-pot",400), img("pot2",400)],
    description: "7-in-1 multi-use programmable pressure cooker, slow cooker, rice cooker, steamer, sauté, yogurt maker and warmer.",
    specs: { Capacity: "6 Quart", Functions: "7-in-1", Material: "Stainless Steel", Wattage: "1000W", Programs: "14 built-in" },
    highlights: ["7 appliances in 1", "Up to 70% faster cooking", "Safe & easy to use", "Easy to clean"],
    inStock: true,
  },
  {
    id: 11, category: "home",
    name: "Philips Air Purifier AC1215",
    brand: "Philips", price: 8999, originalPrice: 14999, rating: 4.4, reviews: 3891,
    badge: "Health Pick",
    images: [img("air-purifier",400), img("philips2",400)],
    description: "Philips Air Purifier removes 99.97% particles including PM2.5, bacteria and viruses. HEPA + Carbon filter.",
    specs: { "Room Coverage": "Up to 323 sq ft", CADR: "270 m3/hr", Filter: "True HEPA + Pre-filter + Carbon", Noise: "33 dB (sleep mode)", "Filter Life": "Up to 1 year" },
    highlights: ["True HEPA filter", "PM2.5 sensor", "Auto mode", "Sleep mode 33dB"],
    inStock: true,
  },
  {
    id: 12, category: "home",
    name: "Dyson V15 Detect Vacuum",
    brand: "Dyson", price: 52900, originalPrice: 62900, rating: 4.7, reviews: 2134,
    badge: "Premium",
    images: [img("dyson-vacuum",400), img("dyson2",400)],
    description: "Dyson V15 Detect with laser technology to illuminate microscopic dust. 60 min run time.",
    specs: { Type: "Cordless Vacuum", Suction: "240 AW", Runtime: "60 minutes", Weight: "3.1 kg", Filter: "HEPA filter", Battery: "2200mAh" },
    highlights: ["Laser dust detection", "60min runtime", "5 cleaner heads", "LCD screen"],
    inStock: true,
  },
  {
    id: 26, category: "home",
    name: "Milton Thermosteel Flip Lid Flask 1000ml",
    brand: "Milton", price: 699, originalPrice: 1299, rating: 4.5, reviews: 34521,
    badge: "46% Off",
    images: [img("flask-milton",400), img("flask2",400)],
    description: "Milton Thermosteel Flask keeps beverages hot for 24 hours and cold for 24 hours.",
    specs: { Capacity: "1000ml", Material: "Stainless Steel 304 Grade", "Hot/Cold": "24 hours each", Weight: "450g", BPA: "BPA Free" },
    highlights: ["24hr hot/cold", "Food grade steel", "Leak proof", "Easy carry handle"],
    inStock: true,
  },
  {
    id: 27, category: "home",
    name: "Prestige Induction Cooktop 2000W",
    brand: "Prestige", price: 2299, originalPrice: 4299, rating: 4.3, reviews: 22341,
    badge: "Energy Saver",
    images: [img("induction-cooktop",400), img("cooktop2",400)],
    description: "Prestige Induction Cooktop with 2000W power, 8 preset menus, and auto shut-off safety feature.",
    specs: { Power: "2000W", Voltage: "220-240V", Menus: "8 preset", "Timer": "0-180 min", Weight: "1.3kg" },
    highlights: ["2000W fast heating", "8 preset menus", "Auto shut-off", "Feather touch buttons"],
    inStock: true,
  },

  // ── Books ─────────────────────────────────────────────────
  {
    id: 13, category: "books",
    name: "Atomic Habits by James Clear",
    brand: "Penguin", price: 499, originalPrice: 799, rating: 4.8, reviews: 45234,
    badge: "Bestseller",
    images: [img("atomic-habits-book",400), img("book2",400)],
    description: "An Easy & Proven Way to Build Good Habits & Break Bad Ones. #1 New York Times bestseller.",
    specs: { Pages: "320", Publisher: "Avery", Language: "English", ISBN: "9780735211292", Format: "Paperback" },
    highlights: ["NYT Bestseller", "Practical framework", "Proven techniques", "Life changing"],
    inStock: true,
  },
  {
    id: 14, category: "books",
    name: "The Psychology of Money",
    brand: "Jaico Publishing", price: 399, originalPrice: 599, rating: 4.7, reviews: 32891,
    badge: "Must Read",
    images: [img("psychology-money",400), img("book3",400)],
    description: "Timeless lessons on wealth, greed, and happiness by Morgan Housel.",
    specs: { Pages: "256", Publisher: "Harriman House", Language: "English", ISBN: "9780857197689", Format: "Paperback" },
    highlights: ["19 short stories", "Financial wisdom", "Easy to read", "Thought-provoking"],
    inStock: true,
  },
  {
    id: 28, category: "books",
    name: "Rich Dad Poor Dad",
    brand: "Plata Publishing", price: 299, originalPrice: 499, rating: 4.6, reviews: 67812,
    badge: "All Time Classic",
    images: [img("rich-dad-book",400), img("book4",400)],
    description: "Robert Kiyosaki's bestseller about financial literacy, investing and how the rich think differently.",
    specs: { Pages: "336", Publisher: "Plata Publishing", Language: "English", Format: "Paperback", Edition: "20th Anniversary" },
    highlights: ["Financial literacy", "Investment basics", "Rich mindset", "Easy language"],
    inStock: true,
  },

  // ── Sports ────────────────────────────────────────────────
  {
    id: 15, category: "sports",
    name: "Yonex Nanoray 10F Badminton Racket",
    brand: "Yonex", price: 1499, originalPrice: 2500, rating: 4.3, reviews: 5612,
    badge: "Pro Choice",
    images: [img("badminton-racket",400), img("yonex2",400)],
    description: "Yonex Nanoray 10F with isometric head shape for larger sweet spot and extra-slim shaft.",
    specs: { Weight: "85g", Balance: "Head Light", Flexibility: "Flexible", String: "BG65 (22 lbs)", Material: "Graphite" },
    highlights: ["Isometric frame", "Extra slim shaft", "Head light balance", "Wide sweet spot"],
    inStock: true,
  },
  {
    id: 16, category: "sports",
    name: "Boldfit Gym Gloves with Wrist Support",
    brand: "Boldfit", price: 399, originalPrice: 799, rating: 4.2, reviews: 8923,
    badge: "Fitness Pick",
    images: [img("gym-gloves",400), img("gloves2",400)],
    description: "Professional gym gloves with wrist support for weight lifting, cross training and cycling.",
    specs: { Material: "Leather + Neoprene", Closure: "Velcro", Sizes: "S, M, L, XL", Wrist: "3-inch support" },
    highlights: ["Anti-slip grip", "Wrist support", "Breathable mesh", "Machine washable"],
    inStock: true,
  },
  {
    id: 29, category: "sports",
    name: "Nivia Storm Football Size 5",
    brand: "Nivia", price: 649, originalPrice: 1299, rating: 4.3, reviews: 12341,
    badge: "50% Off",
    images: [img("football-nivia",400), img("football2",400)],
    description: "Nivia Storm football with rubber bladder and machine stitched panels for durability.",
    specs: { Size: "5 (Standard)", Material: "Synthetic PU", Bladder: "Rubber", Stitching: "Machine stitched", Weight: "410-450g" },
    highlights: ["Regulation size 5", "Durable PU leather", "Long lasting rubber bladder", "Vibrant design"],
    inStock: true,
  },

  // ── Beauty ────────────────────────────────────────────────
  {
    id: 17, category: "beauty",
    name: "L'Oreal Paris Revitalift Day Cream",
    brand: "L'Oreal", price: 699, originalPrice: 1299, rating: 4.4, reviews: 12341,
    badge: "Dermat Tested",
    images: [img("loreal-cream",400), img("cream2",400)],
    description: "L'Oreal Revitalift Anti-Wrinkle + Firming Day Cream with Pro-Retinol and Centella Asiatica.",
    specs: { Weight: "50ml", "Skin Type": "All Skin Types", SPF: "15", "Key Ingredients": "Pro-Retinol, Centella Asiatica", Usage: "Day Cream" },
    highlights: ["Pro-Retinol formula", "24hr hydration", "Firms in 4 weeks", "SPF 15"],
    inStock: true,
  },
  {
    id: 30, category: "beauty",
    name: "Mamaearth Vitamin C Face Serum",
    brand: "Mamaearth", price: 549, originalPrice: 799, rating: 4.3, reviews: 28912,
    badge: "Skin Glow",
    images: [img("vitamin-c-serum",400), img("serum2",400)],
    description: "Mamaearth Vitamin C Face Serum with Turmeric for radiant, glowing skin. 100% natural, toxin-free.",
    specs: { Volume: "30ml", "Key Ingredients": "Vitamin C, Turmeric", "Skin Type": "All Skin Types", Usage: "Day & Night", "Toxin Free": "Yes" },
    highlights: ["Brightens skin", "Reduces dark spots", "Natural ingredients", "Toxin free"],
    inStock: true,
  },

  // ── Toys ──────────────────────────────────────────────────
  {
    id: 18, category: "toys",
    name: "LEGO Technic Bugatti Chiron",
    brand: "LEGO", price: 24999, originalPrice: 34999, rating: 4.9, reviews: 2891,
    badge: "Premium Set",
    images: [img("lego-bugatti",400), img("lego2",400)],
    description: "Build the iconic Bugatti Chiron with 3599 pieces. Features working W16 engine and gearbox.",
    specs: { Pieces: "3599", Age: "16+", Height: "14cm", Width: "56cm", Length: "27cm", "Set Number": "42083" },
    highlights: ["3599 pieces", "Working W16 engine", "Realistic gearbox", "Display stand included"],
    inStock: true,
  },
  {
    id: 31, category: "toys",
    name: "Funskool Monopoly Board Game",
    brand: "Funskool", price: 699, originalPrice: 1299, rating: 4.4, reviews: 9812,
    badge: "Family Fun",
    images: [img("monopoly-game",400), img("boardgame2",400)],
    description: "The classic Monopoly board game for 2-8 players. Buy, sell and trade properties to dominate the board.",
    specs: { Players: "2-8", Age: "8+", "Play Time": "60-180 minutes", Contents: "Board, tokens, cards, dice, hotels/houses" },
    highlights: ["Classic family game", "2-8 players", "Strategic thinking", "Hours of fun"],
    inStock: true,
  },

  // ── Grocery ───────────────────────────────────────────────
  {
    id: 19, category: "grocery",
    name: "Tata Tea Gold 1kg",
    brand: "Tata Tea", price: 389, originalPrice: 450, rating: 4.5, reviews: 23412,
    badge: "Daily Essential",
    images: [img("tata-tea",400), img("tea2",400)],
    description: "Tata Tea Gold - a blend of whole leaf, long leaf and short leaf tea for a rich, golden cup.",
    specs: { Weight: "1 kg", Type: "Black Tea", Origin: "Assam, Darjeeling", Caffeine: "Medium", Form: "Loose Leaf" },
    highlights: ["Premium whole leaf", "Rich golden taste", "Best of 3 grades", "From top gardens"],
    inStock: true,
  },
  {
    id: 20, category: "grocery",
    name: "Amul Butter 500g",
    brand: "Amul", price: 245, originalPrice: 265, rating: 4.7, reviews: 45891,
    badge: "Fresh",
    images: [img("amul-butter",400), img("butter2",400)],
    description: "Amul Butter - Utterly Butterly Delicious. Made from fresh cream.",
    specs: { Weight: "500g", Fat: "80% min", Type: "Salted Butter", Storage: "Keep refrigerated", "Shelf Life": "60 days" },
    highlights: ["Pure cream butter", "Rich taste", "No artificial preservatives", "FSSAI certified"],
    inStock: true,
  },
  {
    id: 32, category: "grocery",
    name: "Aashirvaad Atta Whole Wheat 10kg",
    brand: "Aashirvaad", price: 359, originalPrice: 420, rating: 4.6, reviews: 52341,
    badge: "Best Seller",
    images: [img("aashirvaad-atta",400), img("flour2",400)],
    description: "Aashirvaad Atta made from 100% whole wheat grains, naturally rich in fibre and nutrients.",
    specs: { Weight: "10 kg", Type: "Whole Wheat", Fibre: "High", Gluten: "Present", Storage: "Cool & dry place" },
    highlights: ["100% whole wheat", "High in fibre", "No additives", "Farm fresh grain"],
    inStock: true,
  },
];

// Export for module use
if (typeof module !== 'undefined') {
  module.exports = { CATEGORIES, PRODUCTS };
}
